//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EjbApplicationServiceServiceSoapBinding", Namespace="http://impl.business.sdi.com/")]
public partial class EjbApplicationServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback saveOperationCompleted;
    
    private System.Threading.SendOrPostCallback deleteOperationCompleted;
    
    /// <remarks/>
    public EjbApplicationServiceService() {
        this.Url = "http://localhost:8280/sdi3-7.EJB/ApplicationService";
    }
    
    /// <remarks/>
    public event saveCompletedEventHandler saveCompleted;
    
    /// <remarks/>
    public event deleteCompletedEventHandler deleteCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool save([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] application arg0) {
        object[] results = this.Invoke("save", new object[] {
                    arg0});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsave(application arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("save", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool Endsave(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void saveAsync(application arg0) {
        this.saveAsync(arg0, null);
    }
    
    /// <remarks/>
    public void saveAsync(application arg0, object userState) {
        if ((this.saveOperationCompleted == null)) {
            this.saveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveOperationCompleted);
        }
        this.InvokeAsync("save", new object[] {
                    arg0}, this.saveOperationCompleted, userState);
    }
    
    private void OnsaveOperationCompleted(object arg) {
        if ((this.saveCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.saveCompleted(this, new saveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void delete([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg1Specified) {
        this.Invoke("delete", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult Begindelete(long arg0, bool arg0Specified, long arg1, bool arg1Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("delete", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Enddelete(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void deleteAsync(long arg0, bool arg0Specified, long arg1, bool arg1Specified) {
        this.deleteAsync(arg0, arg0Specified, arg1, arg1Specified, null);
    }
    
    /// <remarks/>
    public void deleteAsync(long arg0, bool arg0Specified, long arg1, bool arg1Specified, object userState) {
        if ((this.deleteOperationCompleted == null)) {
            this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
        }
        this.InvokeAsync("delete", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified}, this.deleteOperationCompleted, userState);
    }
    
    private void OndeleteOperationCompleted(object arg) {
        if ((this.deleteCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public partial class application {
    
    private long tripIdField;
    
    private bool tripIdFieldSpecified;
    
    private long userIdField;
    
    private bool userIdFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long tripId {
        get {
            return this.tripIdField;
        }
        set {
            this.tripIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tripIdSpecified {
        get {
            return this.tripIdFieldSpecified;
        }
        set {
            this.tripIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long userId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userIdSpecified {
        get {
            return this.userIdFieldSpecified;
        }
        set {
            this.userIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void saveCompletedEventHandler(object sender, saveCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class saveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal saveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
