//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EjbRatingServiceServiceSoapBinding", Namespace="http://impl.business.sdi.com/")]
public partial class EjbRatingServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback findLastMonthDoneOperationCompleted;
    
    private System.Threading.SendOrPostCallback findAllOperationCompleted;
    
    private System.Threading.SendOrPostCallback deleteOperationCompleted;
    
    /// <remarks/>
    public EjbRatingServiceService() {
        this.Url = "http://DESKTOP-74U6TKG:8280/sdi3-7.EJB/RatingService";
    }
    
    /// <remarks/>
    public event findLastMonthDoneCompletedEventHandler findLastMonthDoneCompleted;
    
    /// <remarks/>
    public event findAllCompletedEventHandler findAllCompleted;
    
    /// <remarks/>
    public event deleteCompletedEventHandler deleteCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rating[] findLastMonthDone() {
        object[] results = this.Invoke("findLastMonthDone", new object[0]);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindLastMonthDone(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findLastMonthDone", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public rating[] EndfindLastMonthDone(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public void findLastMonthDoneAsync() {
        this.findLastMonthDoneAsync(null);
    }
    
    /// <remarks/>
    public void findLastMonthDoneAsync(object userState) {
        if ((this.findLastMonthDoneOperationCompleted == null)) {
            this.findLastMonthDoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindLastMonthDoneOperationCompleted);
        }
        this.InvokeAsync("findLastMonthDone", new object[0], this.findLastMonthDoneOperationCompleted, userState);
    }
    
    private void OnfindLastMonthDoneOperationCompleted(object arg) {
        if ((this.findLastMonthDoneCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findLastMonthDoneCompleted(this, new findLastMonthDoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rating[] findAll() {
        object[] results = this.Invoke("findAll", new object[0]);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindAll(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findAll", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public rating[] EndfindAll(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public void findAllAsync() {
        this.findAllAsync(null);
    }
    
    /// <remarks/>
    public void findAllAsync(object userState) {
        if ((this.findAllOperationCompleted == null)) {
            this.findAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAllOperationCompleted);
        }
        this.InvokeAsync("findAll", new object[0], this.findAllOperationCompleted, userState);
    }
    
    private void OnfindAllOperationCompleted(object arg) {
        if ((this.findAllCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findAllCompleted(this, new findAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int delete([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("delete", new object[] {
                    arg0,
                    arg0Specified});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begindelete(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("delete", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public int Enddelete(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void deleteAsync(long arg0, bool arg0Specified) {
        this.deleteAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void deleteAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.deleteOperationCompleted == null)) {
            this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
        }
        this.InvokeAsync("delete", new object[] {
                    arg0,
                    arg0Specified}, this.deleteOperationCompleted, userState);
    }
    
    private void OndeleteOperationCompleted(object arg) {
        if ((this.deleteCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public partial class rating {
    
    private string commentField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private long seatAboutTripIdField;
    
    private bool seatAboutTripIdFieldSpecified;
    
    private long seatAboutUserIdField;
    
    private bool seatAboutUserIdFieldSpecified;
    
    private long seatFromTripIdField;
    
    private bool seatFromTripIdFieldSpecified;
    
    private long seatFromUserIdField;
    
    private bool seatFromUserIdFieldSpecified;
    
    private int valueField;
    
    private bool valueFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatAboutTripId {
        get {
            return this.seatAboutTripIdField;
        }
        set {
            this.seatAboutTripIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatAboutTripIdSpecified {
        get {
            return this.seatAboutTripIdFieldSpecified;
        }
        set {
            this.seatAboutTripIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatAboutUserId {
        get {
            return this.seatAboutUserIdField;
        }
        set {
            this.seatAboutUserIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatAboutUserIdSpecified {
        get {
            return this.seatAboutUserIdFieldSpecified;
        }
        set {
            this.seatAboutUserIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatFromTripId {
        get {
            return this.seatFromTripIdField;
        }
        set {
            this.seatFromTripIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatFromTripIdSpecified {
        get {
            return this.seatFromTripIdFieldSpecified;
        }
        set {
            this.seatFromTripIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatFromUserId {
        get {
            return this.seatFromUserIdField;
        }
        set {
            this.seatFromUserIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatFromUserIdSpecified {
        get {
            return this.seatFromUserIdFieldSpecified;
        }
        set {
            this.seatFromUserIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueSpecified {
        get {
            return this.valueFieldSpecified;
        }
        set {
            this.valueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findLastMonthDoneCompletedEventHandler(object sender, findLastMonthDoneCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findLastMonthDoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findLastMonthDoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public rating[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((rating[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findAllCompletedEventHandler(object sender, findAllCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public rating[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((rating[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}
