//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EjbTripServiceServiceSoapBinding", Namespace="http://impl.business.sdi.com/")]
public partial class EjbTripServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback saveTripOperationCompleted;
    
    private System.Threading.SendOrPostCallback currentTravelsPromoterOperationCompleted;
    
    private System.Threading.SendOrPostCallback listActiveTripsOperationCompleted;
    
    private System.Threading.SendOrPostCallback pendingUsersOperationCompleted;
    
    private System.Threading.SendOrPostCallback tripsTakePartOfOperationCompleted;
    
    private System.Threading.SendOrPostCallback updateTripsStatusTaskOperationCompleted;
    
    private System.Threading.SendOrPostCallback findTripOperationCompleted;
    
    private System.Threading.SendOrPostCallback updateOperationCompleted;
    
    private System.Threading.SendOrPostCallback tripsAcceptedOperationCompleted;
    
    private System.Threading.SendOrPostCallback travelsPromoterOperationCompleted;
    
    /// <remarks/>
    public EjbTripServiceService() {
        this.Url = "http://DESKTOP-74U6TKG:8280/sdi3-7.EJB/TripService";
    }
    
    /// <remarks/>
    public event saveTripCompletedEventHandler saveTripCompleted;
    
    /// <remarks/>
    public event currentTravelsPromoterCompletedEventHandler currentTravelsPromoterCompleted;
    
    /// <remarks/>
    public event listActiveTripsCompletedEventHandler listActiveTripsCompleted;
    
    /// <remarks/>
    public event pendingUsersCompletedEventHandler pendingUsersCompleted;
    
    /// <remarks/>
    public event tripsTakePartOfCompletedEventHandler tripsTakePartOfCompleted;
    
    /// <remarks/>
    public event updateTripsStatusTaskCompletedEventHandler updateTripsStatusTaskCompleted;
    
    /// <remarks/>
    public event findTripCompletedEventHandler findTripCompleted;
    
    /// <remarks/>
    public event updateCompletedEventHandler updateCompleted;
    
    /// <remarks/>
    public event tripsAcceptedCompletedEventHandler tripsAcceptedCompleted;
    
    /// <remarks/>
    public event travelsPromoterCompletedEventHandler travelsPromoterCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void saveTrip([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0) {
        this.Invoke("saveTrip", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsaveTrip(trip arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("saveTrip", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndsaveTrip(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void saveTripAsync(trip arg0) {
        this.saveTripAsync(arg0, null);
    }
    
    /// <remarks/>
    public void saveTripAsync(trip arg0, object userState) {
        if ((this.saveTripOperationCompleted == null)) {
            this.saveTripOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveTripOperationCompleted);
        }
        this.InvokeAsync("saveTrip", new object[] {
                    arg0}, this.saveTripOperationCompleted, userState);
    }
    
    private void OnsaveTripOperationCompleted(object arg) {
        if ((this.saveTripCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.saveTripCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] currentTravelsPromoter([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg1Specified) {
        object[] results = this.Invoke("currentTravelsPromoter", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincurrentTravelsPromoter(long arg0, bool arg0Specified, System.DateTime arg1, bool arg1Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("currentTravelsPromoter", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndcurrentTravelsPromoter(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void currentTravelsPromoterAsync(long arg0, bool arg0Specified, System.DateTime arg1, bool arg1Specified) {
        this.currentTravelsPromoterAsync(arg0, arg0Specified, arg1, arg1Specified, null);
    }
    
    /// <remarks/>
    public void currentTravelsPromoterAsync(long arg0, bool arg0Specified, System.DateTime arg1, bool arg1Specified, object userState) {
        if ((this.currentTravelsPromoterOperationCompleted == null)) {
            this.currentTravelsPromoterOperationCompleted = new System.Threading.SendOrPostCallback(this.OncurrentTravelsPromoterOperationCompleted);
        }
        this.InvokeAsync("currentTravelsPromoter", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified}, this.currentTravelsPromoterOperationCompleted, userState);
    }
    
    private void OncurrentTravelsPromoterOperationCompleted(object arg) {
        if ((this.currentTravelsPromoterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.currentTravelsPromoterCompleted(this, new currentTravelsPromoterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] listActiveTrips([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("listActiveTrips", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistActiveTrips(System.DateTime arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listActiveTrips", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndlistActiveTrips(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void listActiveTripsAsync(System.DateTime arg0, bool arg0Specified) {
        this.listActiveTripsAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void listActiveTripsAsync(System.DateTime arg0, bool arg0Specified, object userState) {
        if ((this.listActiveTripsOperationCompleted == null)) {
            this.listActiveTripsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistActiveTripsOperationCompleted);
        }
        this.InvokeAsync("listActiveTrips", new object[] {
                    arg0,
                    arg0Specified}, this.listActiveTripsOperationCompleted, userState);
    }
    
    private void OnlistActiveTripsOperationCompleted(object arg) {
        if ((this.listActiveTripsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listActiveTripsCompleted(this, new listActiveTripsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user[] pendingUsers([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg1Specified) {
        object[] results = this.Invoke("pendingUsers", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified});
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginpendingUsers(long arg0, bool arg0Specified, long arg1, bool arg1Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("pendingUsers", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public user[] EndpendingUsers(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public void pendingUsersAsync(long arg0, bool arg0Specified, long arg1, bool arg1Specified) {
        this.pendingUsersAsync(arg0, arg0Specified, arg1, arg1Specified, null);
    }
    
    /// <remarks/>
    public void pendingUsersAsync(long arg0, bool arg0Specified, long arg1, bool arg1Specified, object userState) {
        if ((this.pendingUsersOperationCompleted == null)) {
            this.pendingUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpendingUsersOperationCompleted);
        }
        this.InvokeAsync("pendingUsers", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified}, this.pendingUsersOperationCompleted, userState);
    }
    
    private void OnpendingUsersOperationCompleted(object arg) {
        if ((this.pendingUsersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.pendingUsersCompleted(this, new pendingUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] tripsTakePartOf([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("tripsTakePartOf", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegintripsTakePartOf(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("tripsTakePartOf", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndtripsTakePartOf(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void tripsTakePartOfAsync(long arg0, bool arg0Specified) {
        this.tripsTakePartOfAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void tripsTakePartOfAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.tripsTakePartOfOperationCompleted == null)) {
            this.tripsTakePartOfOperationCompleted = new System.Threading.SendOrPostCallback(this.OntripsTakePartOfOperationCompleted);
        }
        this.InvokeAsync("tripsTakePartOf", new object[] {
                    arg0,
                    arg0Specified}, this.tripsTakePartOfOperationCompleted, userState);
    }
    
    private void OntripsTakePartOfOperationCompleted(object arg) {
        if ((this.tripsTakePartOfCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.tripsTakePartOfCompleted(this, new tripsTakePartOfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void updateTripsStatusTask() {
        this.Invoke("updateTripsStatusTask", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginupdateTripsStatusTask(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("updateTripsStatusTask", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void EndupdateTripsStatusTask(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void updateTripsStatusTaskAsync() {
        this.updateTripsStatusTaskAsync(null);
    }
    
    /// <remarks/>
    public void updateTripsStatusTaskAsync(object userState) {
        if ((this.updateTripsStatusTaskOperationCompleted == null)) {
            this.updateTripsStatusTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateTripsStatusTaskOperationCompleted);
        }
        this.InvokeAsync("updateTripsStatusTask", new object[0], this.updateTripsStatusTaskOperationCompleted, userState);
    }
    
    private void OnupdateTripsStatusTaskOperationCompleted(object arg) {
        if ((this.updateTripsStatusTaskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.updateTripsStatusTaskCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip findTrip([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findTrip", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindTrip(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findTrip", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip EndfindTrip(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip)(results[0]));
    }
    
    /// <remarks/>
    public void findTripAsync(long arg0, bool arg0Specified) {
        this.findTripAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findTripAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findTripOperationCompleted == null)) {
            this.findTripOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindTripOperationCompleted);
        }
        this.InvokeAsync("findTrip", new object[] {
                    arg0,
                    arg0Specified}, this.findTripOperationCompleted, userState);
    }
    
    private void OnfindTripOperationCompleted(object arg) {
        if ((this.findTripCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findTripCompleted(this, new findTripCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void update([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0) {
        this.Invoke("update", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginupdate(trip arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("update", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endupdate(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void updateAsync(trip arg0) {
        this.updateAsync(arg0, null);
    }
    
    /// <remarks/>
    public void updateAsync(trip arg0, object userState) {
        if ((this.updateOperationCompleted == null)) {
            this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
        }
        this.InvokeAsync("update", new object[] {
                    arg0}, this.updateOperationCompleted, userState);
    }
    
    private void OnupdateOperationCompleted(object arg) {
        if ((this.updateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.updateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] tripsAccepted([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("tripsAccepted", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegintripsAccepted(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("tripsAccepted", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndtripsAccepted(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void tripsAcceptedAsync(long arg0, bool arg0Specified) {
        this.tripsAcceptedAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void tripsAcceptedAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.tripsAcceptedOperationCompleted == null)) {
            this.tripsAcceptedOperationCompleted = new System.Threading.SendOrPostCallback(this.OntripsAcceptedOperationCompleted);
        }
        this.InvokeAsync("tripsAccepted", new object[] {
                    arg0,
                    arg0Specified}, this.tripsAcceptedOperationCompleted, userState);
    }
    
    private void OntripsAcceptedOperationCompleted(object arg) {
        if ((this.tripsAcceptedCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.tripsAcceptedCompleted(this, new tripsAcceptedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] travelsPromoter([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("travelsPromoter", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegintravelsPromoter(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("travelsPromoter", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndtravelsPromoter(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void travelsPromoterAsync(long arg0, bool arg0Specified) {
        this.travelsPromoterAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void travelsPromoterAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.travelsPromoterOperationCompleted == null)) {
            this.travelsPromoterOperationCompleted = new System.Threading.SendOrPostCallback(this.OntravelsPromoterOperationCompleted);
        }
        this.InvokeAsync("travelsPromoter", new object[] {
                    arg0,
                    arg0Specified}, this.travelsPromoterOperationCompleted, userState);
    }
    
    private void OntravelsPromoterOperationCompleted(object arg) {
        if ((this.travelsPromoterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.travelsPromoterCompleted(this, new travelsPromoterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public partial class trip {
    
    private System.DateTime arrivalDateField;
    
    private bool arrivalDateFieldSpecified;
    
    private int availablePaxField;
    
    private bool availablePaxFieldSpecified;
    
    private System.DateTime closingDateField;
    
    private bool closingDateFieldSpecified;
    
    private string commentsField;
    
    private addressPoint departureField;
    
    private System.DateTime departureDateField;
    
    private bool departureDateFieldSpecified;
    
    private addressPoint destinationField;
    
    private double estimatedCostField;
    
    private bool estimatedCostFieldSpecified;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private int maxPaxField;
    
    private bool maxPaxFieldSpecified;
    
    private long promoterIdField;
    
    private bool promoterIdFieldSpecified;
    
    private tripStatus statusField;
    
    private bool statusFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime arrivalDate {
        get {
            return this.arrivalDateField;
        }
        set {
            this.arrivalDateField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool arrivalDateSpecified {
        get {
            return this.arrivalDateFieldSpecified;
        }
        set {
            this.arrivalDateFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int availablePax {
        get {
            return this.availablePaxField;
        }
        set {
            this.availablePaxField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool availablePaxSpecified {
        get {
            return this.availablePaxFieldSpecified;
        }
        set {
            this.availablePaxFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime closingDate {
        get {
            return this.closingDateField;
        }
        set {
            this.closingDateField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool closingDateSpecified {
        get {
            return this.closingDateFieldSpecified;
        }
        set {
            this.closingDateFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public addressPoint departure {
        get {
            return this.departureField;
        }
        set {
            this.departureField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime departureDate {
        get {
            return this.departureDateField;
        }
        set {
            this.departureDateField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool departureDateSpecified {
        get {
            return this.departureDateFieldSpecified;
        }
        set {
            this.departureDateFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public addressPoint destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double estimatedCost {
        get {
            return this.estimatedCostField;
        }
        set {
            this.estimatedCostField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool estimatedCostSpecified {
        get {
            return this.estimatedCostFieldSpecified;
        }
        set {
            this.estimatedCostFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int maxPax {
        get {
            return this.maxPaxField;
        }
        set {
            this.maxPaxField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxPaxSpecified {
        get {
            return this.maxPaxFieldSpecified;
        }
        set {
            this.maxPaxFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long promoterId {
        get {
            return this.promoterIdField;
        }
        set {
            this.promoterIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool promoterIdSpecified {
        get {
            return this.promoterIdFieldSpecified;
        }
        set {
            this.promoterIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public tripStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public partial class addressPoint {
    
    private string addressField;
    
    private string cityField;
    
    private string countryField;
    
    private string stateField;
    
    private waypoint waypointField;
    
    private string zipCodeField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public waypoint waypoint {
        get {
            return this.waypointField;
        }
        set {
            this.waypointField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string zipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public partial class waypoint {
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public partial class user {
    
    private string emailField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private string loginField;
    
    private string nameField;
    
    private string passwordField;
    
    private userStatus statusField;
    
    private bool statusFieldSpecified;
    
    private string surnameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public userStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public enum userStatus {
    
    /// <comentarios/>
    ACTIVE,
    
    /// <comentarios/>
    CANCELLED,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public enum tripStatus {
    
    /// <comentarios/>
    OPEN,
    
    /// <comentarios/>
    CLOSED,
    
    /// <comentarios/>
    CANCELLED,
    
    /// <comentarios/>
    DONE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void saveTripCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void currentTravelsPromoterCompletedEventHandler(object sender, currentTravelsPromoterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class currentTravelsPromoterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal currentTravelsPromoterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void listActiveTripsCompletedEventHandler(object sender, listActiveTripsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listActiveTripsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listActiveTripsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void pendingUsersCompletedEventHandler(object sender, pendingUsersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class pendingUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal pendingUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void tripsTakePartOfCompletedEventHandler(object sender, tripsTakePartOfCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tripsTakePartOfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal tripsTakePartOfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void updateTripsStatusTaskCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findTripCompletedEventHandler(object sender, findTripCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findTripCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findTripCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void updateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void tripsAcceptedCompletedEventHandler(object sender, tripsAcceptedCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tripsAcceptedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal tripsAcceptedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void travelsPromoterCompletedEventHandler(object sender, travelsPromoterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class travelsPromoterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal travelsPromoterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}
